version: '3.3'

services:

  elasticsearch:
    container_name: elasticsearch
    # build: .
    image: docker pull tunnm/docker-es-cococ-tokenizer:7.12.1
    ports:
      - "9200:9200"
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: ".watches,.triggered_watches,.watcher-history-*"
      network.host: "0.0.0.0"
    ulimits:
      nofile:
         soft: 65536
         hard: 65536
      memlock:
        hard: -1
        soft: -1
